[".zplug"]
    type = "archive"
    url = "https://github.com/zplug/zplug/archive/master.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"
[".zsh/antidote"]
    type = "archive"
    url = "https://github.com/mattmc3/antidote/archive/master.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"
