[".zplug"]
    type = "archive"
    url = "https://github.com/zplug/zplug/archive/master.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"
[".zsh/iterm2_integration.zsh"]
    type = "file"
    url = "https://iterm2.com/shell_integration/zsh"
    refreshPeriod = "168h"